blank_issues_enabled: true
contact_links:
  - name: âœï¸ Start a Discussion!
    url: https://github.com/SanjulaGanepola/github-local-actions/discussions
    about: You can ask for help here.
  - name: ğŸ™ Learn How to Contribute!
    url: https://github.com/SanjulaGanepola/github-local-actions/blob/main/CONTRIBUTING.md
    about: Check out the contributing guidelines.